package com.appgeneration.magmanager.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MAGAZINE.
 */
public class Magazine {

    private Long id;
    private String name;
    private String bannerLeft;
    private String bannerRight;
    private String bannerTop;
    private String bannerBottom;

    public Magazine() {
    }

    public Magazine(Long id) {
        this.id = id;
    }

    public Magazine(Long id, String name, String bannerLeft, String bannerRight, String bannerTop, String bannerBottom) {
        this.id = id;
        this.name = name;
        this.bannerLeft = bannerLeft;
        this.bannerRight = bannerRight;
        this.bannerTop = bannerTop;
        this.bannerBottom = bannerBottom;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBannerLeft() {
        return bannerLeft;
    }

    public void setBannerLeft(String bannerLeft) {
        this.bannerLeft = bannerLeft;
    }

    public String getBannerRight() {
        return bannerRight;
    }

    public void setBannerRight(String bannerRight) {
        this.bannerRight = bannerRight;
    }

    public String getBannerTop() {
        return bannerTop;
    }

    public void setBannerTop(String bannerTop) {
        this.bannerTop = bannerTop;
    }

    public String getBannerBottom() {
        return bannerBottom;
    }

    public void setBannerBottom(String bannerBottom) {
        this.bannerBottom = bannerBottom;
    }

}
