package com.appgeneration.magmanager.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUBSCRIPTION.
 */
public class Subscription {

    private Long id;
    private String title;
    private Long duration;
    private String cover;
    private String price;

    public Subscription() {
    }

    public Subscription(Long id) {
        this.id = id;
    }

    public Subscription(Long id, String title, Long duration, String cover, String price) {
        this.id = id;
        this.title = title;
        this.duration = duration;
        this.cover = cover;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

}
